name: Linux

on:
  push:
    paths:
    - '.github/workflows/**'
    - 'JuceLibraryCode/**'
    - 'PluginGenerator/**'
    - 'Plugins/**'
    - 'Resources/**'
    - 'Source/**'
    - 'CMakeLists.txt'
    - 'HelperFunctions.cmake'

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        sudo apt update
        cd Resources/Scripts
        sudo ./install_linux_dependencies.sh
        cd ../../Build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: |
        cd Build
        make all
#    - name: test
#      run: cd build && ctest
    - name: deploy_test
      if: github.ref == 'refs/heads/testing'
      env:
        bintrayUser: ${{ secrets.bintrayUsername }}
        bintrayApiKey: ${{ secrets.bintrayApiKey }}
      run: |
        gui_ver=$(git describe --tags $(git rev-list --tags --max-count=1))
        cd Build
        cp -r Release open-ephys
        cp -r ../Resources/DataFiles open-ephys
        cp -r ../Licenses open-ephys
        zipfile=open-ephys-${gui_ver}-linux-beta.zip
        zip -r $zipfile open-ephys
        user_info="$bintrayUser:$bintrayApiKey"
        curl -T $zipfile --user $user_info https://api.bintray.com/content/open-ephys-gui/Test/Test-linux/$gui_ver/$zipfile
        curl -X POST --user $user_info https://api.bintray.com/content/open-ephys-gui/Test/Test-linux/$gui_ver/publish
        cd ../Resources/Installers/Linux/Open-Ephys_Installer
        mkdir -p usr/local/bin/open-ephys-gui
        cp -r ../../../../Build/Release/* usr/local/bin/open-ephys-gui
        cp ../../../Scripts/40-open-ephys.rules usr/local/bin/open-ephys-gui
        cd ..
        dpkg-deb --build Open-Ephys_Installer
        installer=open-ephys-gui-${gui_ver}-beta.deb
        mv -v Open-Ephys_Installer.deb $installer
        curl -T $installer --user $user_info https://api.bintray.com/content/open-ephys-gui/Test-Installer/Test-Installer-linux/$gui_ver/$installer
        curl -X POST --user $user_info https://api.bintray.com/content/open-ephys-gui/Test-Installer/Test-Installer-linux/$gui_ver/publish
      shell: bash
    - name: deploy_release
      if: github.ref == 'refs/heads/master'
      env:
        bintrayUser: ${{ secrets.bintrayUsername }}
        bintrayApiKey: ${{ secrets.bintrayApiKey }}
      run: |
        gui_ver=$(git describe --tags $(git rev-list --tags --max-count=1))
        cd Build
        cp -r Release open-ephys
        cp -r ../Resources/DataFiles open-ephys
        cp -r ../Licenses open-ephys
        zipfile=open-ephys-${gui_ver}-linux.zip
        zip -r $zipfile open-ephys
        user_info="$bintrayUser:$bintrayApiKey"
        curl -T $zipfile --user $user_info https://api.bintray.com/content/open-ephys-gui/Release/Release-linux/$gui_ver/$zipfile
        curl -X POST --user $user_info https://api.bintray.com/content/open-ephys-gui/Release/Release-linux/$gui_ver/publish
        cd ../Resources/Installers/Linux/Open-Ephys_Installer
        mkdir -p usr/local/bin/open-ephys-gui
        cp -r ../../../../Build/Release/* usr/local/bin/open-ephys-gui
        cp ../../../Scripts/40-open-ephys.rules usr/local/bin/open-ephys-gui
        cd ..
        dpkg-deb --build Open-Ephys_Installer
        installer=open-ephys-gui-${gui_ver}.deb
        mv Open-Ephys_Installer.deb $installer
        curl -T $installer --user $user_info https://api.bintray.com/content/open-ephys-gui/Release-Installer/Release-Installer-linux/$gui_ver/$installer
        curl -X POST --user $user_info https://api.bintray.com/content/open-ephys-gui/Release-Installer/Release-Installer-linux/$gui_ver/publish
      shell: bash
