name: Linux

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        cd Build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
        cd ../Resources/Scripts
        sudo apt update
        sudo ./install_linux_dependencies.sh
    - name: build
      run: cmake --build Build
#    - name: test
#      run: cd build && ctest
