name: macOS

on: [push]

jobs:
  build-osx:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        cd Build 
        cmake -G "Xcode" ..
    - name: build
      run: |
        cd Build 
        xcodebuild -project open-ephys-GUI.xcodeproj -scheme=ALL_BUILD 
#    - name: test
#      run: cd build && ctest
