name: Windows

on:
  push:
    paths:
    - '.github/workflows/**'
    - 'JuceLibraryCode/**'
    - 'PluginGenerator/**'
    - 'Plugins/**'
    - 'Resources/**'
    - 'Source/**'
    - 'CMakeLists.txt'
    - 'HelperFunctions.cmake'

jobs:

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        cd Build 
        cmake -G "Visual Studio 16 2019" -A x64 ..
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: build
      run: |
        msbuild Build/ALL_BUILD.vcxproj -p:Configuration=Release -p:Platform=x64
#    - name: test
#      run: cd build && ctest
    - name: deploy_test
      if: github.ref == 'refs/heads/testing'
      env:
        bintrayUser: ${{ secrets.bintrayUsername }}
        bintrayApiKey: ${{ secrets.bintrayApiKey }}
      run: |
        cd Build
        cp -r Release open-ephys
        cp -r ../Resources/DLLs/FrontPanelUSB-DriverOnly-4.5.5.exe open-ephys
        cp -r ../Resources/DataFiles open-ephys
        cp -r ../Licenses open-ephys
        gui_ver=$(git describe --tags $(git rev-list --tags --max-count=1))
        zipfile=open-ephys-${gui_ver}-windows-beta.zip
        powershell Compress-Archive -Path "open-ephys" -DestinationPath ${zipfile}
        user_info="$bintrayUser:$bintrayApiKey"
        curl -T $zipfile --user $user_info https://api.bintray.com/content/open-ephys-gui/Test/Test-windows/$gui_ver/$zipfile
        curl -X POST --user $user_info https://api.bintray.com/content/open-ephys-gui/Test/Test-windows/$gui_ver/publish
        cd ../Resources/Installers/Windows
        iscc "windows_installer_script.iss"
        installer=Install-Open-Ephys-GUI-${gui_ver}-beta.exe
        mv Open-Ephys_Installer.exe $installer
        curl -T $installer --user $user_info https://api.bintray.com/content/open-ephys-gui/Test-Installer/Test-Installer-windows/$gui_ver/$installer
        curl -X POST --user $user_info https://api.bintray.com/content/open-ephys-gui/Test-Installer/Test-Installer-windows/$gui_ver/publish
      shell: bash
    - name: deploy_release
      if: github.ref == 'refs/heads/master'
      env:
        bintrayUser: ${{ secrets.bintrayUsername }}
        bintrayApiKey: ${{ secrets.bintrayApiKey }}
      run: |
        cd Build
        cp -r Release open-ephys
        cp -r ../Resources/DLLs/FrontPanelUSB-DriverOnly-4.5.5.exe open-ephys
        cp -r ../Resources/DataFiles open-ephys
        cp -r ../Licenses open-ephys
        gui_ver=$(git describe --tags $(git rev-list --tags --max-count=1))
        zipfile=open-ephys-${gui_ver}-windows.zip
        powershell Compress-Archive -Path "open-ephys" -DestinationPath ${zipfile}
        user_info="$bintrayUser:$bintrayApiKey"
        curl -T $zipfile --user $user_info https://api.bintray.com/content/open-ephys-gui/Release/Release-windows/$gui_ver/$zipfile
        curl -X POST --user $user_info https://api.bintray.com/content/open-ephys-gui/Release/Release-windows/$gui_ver/publish
        cd ../Resources/Installers/Windows
        iscc "windows_installer_script.iss"
        installer=Install-Open-Ephys-GUI-${gui_ver}.exe
        mv Open-Ephys_Installer.exe $installer
        curl -T $installer --user $user_info https://api.bintray.com/content/open-ephys-gui/Release-Installer/Release-Installer-windows/$gui_ver/$installer
        curl -X POST --user $user_info https://api.bintray.com/content/open-ephys-gui/Release-Installer/Release-Installer-windows/$gui_ver/publish
      shell: bash
