name: Windows

on: [push]

jobs:

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        cd Build 
        cmake -G "Visual Studio 16 2019" -A x64 ..
    - name: build
      run: cmake --build Build
#    - name: test
#      run: cd build && ctest

